# Generated by Django 6.0.1 on 2026-01-18 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('duda', models.TextField(verbose_name='Duda o Consulta')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Envío')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del Usuario')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='Navegador')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('enviado_make', models.BooleanField(default=False, verbose_name='Enviado a Make')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del Administrador')),
            ],
            options={
                'verbose_name': 'Consulta de Asesoría',
                'verbose_name_plural': 'Consultas de Asesoría',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('pais', models.CharField(max_length=100, verbose_name='País de Origen')),
                ('tipo_servicio', models.CharField(max_length=100, verbose_name='Tipo de Servicio')),
                ('mensaje', models.TextField(verbose_name='Descripción del Proyecto')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Envío')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del Usuario')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='Navegador')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('enviado_make', models.BooleanField(default=False, verbose_name='Enviado a Make')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del Administrador')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes de Cotización',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=300, verbose_name='Extracto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('featured_image', models.ImageField(upload_to='blog/', verbose_name='Imagen Destacada')),
                ('category', models.CharField(choices=[('eventos', 'Eventos'), ('logistica', 'Logística'), ('comercio', 'Comercio Internacional'), ('tendencias', 'Tendencias')], default='eventos', max_length=20)),
                ('author', models.CharField(default='Equipo Pacunato', max_length=100)),
                ('read_time', models.IntegerField(default=3, verbose_name='Tiempo de Lectura (min)')),
                ('views', models.IntegerField(default=0, verbose_name='Vistas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='¿Destacado?')),
                ('is_published', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='website.blogtag')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
