# Generated by Django 6.0.1 on 2026-01-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudcotizacion',
            old_name='pais',
            new_name='pais_origen',
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='pais_destino',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='País de Destino'),
            preserve_default=False,
        ),
    ]
