# Generated by Django 6.0.1 on 2026-01-19 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_pais_solicitudcotizacion_pais_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('subscribed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de suscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador')),
                ('source_page', models.CharField(blank=True, max_length=200, verbose_name='Página de origen')),
                ('consent_given', models.BooleanField(default=True, verbose_name='Consentimiento')),
                ('consent_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha consentimiento')),
                ('unsubscribed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('sent_to_make', models.BooleanField(default=False, verbose_name='Enviado a Make')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Suscriptor Newsletter',
                'verbose_name_plural': 'Suscriptores Newsletter',
                'ordering': ['-subscribed_date'],
            },
        ),
    ]
