# Generated by Django 6.0.1 on 2026-01-19 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='blog/', verbose_name='Imagen Destacada'),
        ),
        migrations.CreateModel(
            name='BlogPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='Navegador/Dispositivo')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Vista')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='website.blogpost')),
            ],
            options={
                'verbose_name': 'Vista de Artículo',
                'verbose_name_plural': 'Vistas de Artículos',
                'ordering': ['-viewed_at'],
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
