# Generated by Django 6.0.1 on 2026-04-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_blogtag_options_alter_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Pega aquí la URL de la imagen subida a Cloudinary', max_length=500, verbose_name='URL de Imagen (Cloudinary)'),
        ),
    ]
