# Generated by Django 6.0.1 on 2026-04-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_blogpost_featured_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudGuia',
            fields=[
            ],
            options={
                'verbose_name': 'Solicitud de Guía',
                'verbose_name_plural': 'Solicitudes de Guía de Importación',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.newslettersubscriber',),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='source_page',
            field=models.CharField(blank=True, max_length=200, verbose_name='Página de Origen'),
        ),
    ]
